package com.bs.glr.bean;

import java.util.Date;

public class BsHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_history.id
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_history.uid
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_history.gid
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_history.udate
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    private Date udate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_history.status
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_history.gbalance
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    private String gbalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_history.uname
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_history.gname
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    private String gname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_history.id
     *
     * @return the value of bs_history.id
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_history.id
     *
     * @param id the value for bs_history.id
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_history.uid
     *
     * @return the value of bs_history.uid
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_history.uid
     *
     * @param uid the value for bs_history.uid
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_history.gid
     *
     * @return the value of bs_history.gid
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_history.gid
     *
     * @param gid the value for bs_history.gid
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_history.udate
     *
     * @return the value of bs_history.udate
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    public Date getUdate() {
        return udate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_history.udate
     *
     * @param udate the value for bs_history.udate
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    public void setUdate(Date udate) {
        this.udate = udate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_history.status
     *
     * @return the value of bs_history.status
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_history.status
     *
     * @param status the value for bs_history.status
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_history.gbalance
     *
     * @return the value of bs_history.gbalance
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    public String getGbalance() {
        return gbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_history.gbalance
     *
     * @param gbalance the value for bs_history.gbalance
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    public void setGbalance(String gbalance) {
        this.gbalance = gbalance == null ? null : gbalance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_history.uname
     *
     * @return the value of bs_history.uname
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_history.uname
     *
     * @param uname the value for bs_history.uname
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_history.gname
     *
     * @return the value of bs_history.gname
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_history.gname
     *
     * @param gname the value for bs_history.gname
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }
}