package com.bs.glr.bean;

public class BsReturnData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_return_data.id
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_return_data.return_data
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    private String returnData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_return_data.status
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_return_data.id
     *
     * @return the value of bs_return_data.id
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_return_data.id
     *
     * @param id the value for bs_return_data.id
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_return_data.return_data
     *
     * @return the value of bs_return_data.return_data
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    public String getReturnData() {
        return returnData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_return_data.return_data
     *
     * @param returnData the value for bs_return_data.return_data
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    public void setReturnData(String returnData) {
        this.returnData = returnData == null ? null : returnData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_return_data.status
     *
     * @return the value of bs_return_data.status
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_return_data.status
     *
     * @param status the value for bs_return_data.status
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}