package com.bs.glr.bean;

public class BsStData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_st_data.id
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_st_data.st_data
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    private String stData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_st_data.status
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_st_data.id
     *
     * @return the value of bs_st_data.id
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_st_data.id
     *
     * @param id the value for bs_st_data.id
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_st_data.st_data
     *
     * @return the value of bs_st_data.st_data
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    public String getStData() {
        return stData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_st_data.st_data
     *
     * @param stData the value for bs_st_data.st_data
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    public void setStData(String stData) {
        this.stData = stData == null ? null : stData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_st_data.status
     *
     * @return the value of bs_st_data.status
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_st_data.status
     *
     * @param status the value for bs_st_data.status
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}