package com.bs.glr.mapper;

import com.bs.glr.bean.BsHistory;
import com.bs.glr.bean.BsHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BsHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_history
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    long countByExample(BsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_history
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    int deleteByExample(BsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_history
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_history
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    int insert(BsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_history
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    int insertSelective(BsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_history
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    List<BsHistory> selectByExample(BsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_history
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    BsHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_history
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    int updateByExampleSelective(@Param("record") BsHistory record, @Param("example") BsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_history
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    int updateByExample(@Param("record") BsHistory record, @Param("example") BsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_history
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    int updateByPrimaryKeySelective(BsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_history
     *
     * @mbg.generated Tue Dec 13 19:33:37 CST 2022
     */
    int updateByPrimaryKey(BsHistory record);
}