package com.bs.glr.mapper;

import com.bs.glr.bean.BsReturnData;
import com.bs.glr.bean.BsReturnDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BsReturnDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_return_data
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    long countByExample(BsReturnDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_return_data
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    int deleteByExample(BsReturnDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_return_data
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_return_data
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    int insert(BsReturnData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_return_data
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    int insertSelective(BsReturnData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_return_data
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    List<BsReturnData> selectByExample(BsReturnDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_return_data
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    BsReturnData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_return_data
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    int updateByExampleSelective(@Param("record") BsReturnData record, @Param("example") BsReturnDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_return_data
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    int updateByExample(@Param("record") BsReturnData record, @Param("example") BsReturnDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_return_data
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    int updateByPrimaryKeySelective(BsReturnData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_return_data
     *
     * @mbg.generated Wed Dec 14 20:03:17 CST 2022
     */
    int updateByPrimaryKey(BsReturnData record);
}