package com.bs.glr.mapper;

import com.bs.glr.bean.BsStData;
import com.bs.glr.bean.BsStDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BsStDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_st_data
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    long countByExample(BsStDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_st_data
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    int deleteByExample(BsStDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_st_data
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_st_data
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    int insert(BsStData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_st_data
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    int insertSelective(BsStData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_st_data
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    List<BsStData> selectByExample(BsStDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_st_data
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    BsStData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_st_data
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    int updateByExampleSelective(@Param("record") BsStData record, @Param("example") BsStDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_st_data
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    int updateByExample(@Param("record") BsStData record, @Param("example") BsStDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_st_data
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    int updateByPrimaryKeySelective(BsStData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_st_data
     *
     * @mbg.generated Wed Dec 14 19:53:34 CST 2022
     */
    int updateByPrimaryKey(BsStData record);
}